language: node_js
node_js:
  - "8"
  - "9"
before_install:
   # yüklemedn önce şimdilik işlem yok
install:
  - npm install
services:
  - mongodb
env:
  # mongo db şifreleri
  - MONGO_ATLAS_PWD="med177"
  - MONGO_XEN_PWD="034188Me"
script:
  - npm start
